[package]
name = "methods-guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
evm-core = { path = "../../core", default-features = false }
risc0-zkvm = { version = "0.15.1", default-features = false, features = [ "std" ] }
